version: "3.8"
services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile.pgredis
    container_name: pgredis
    restart: always
    ports:
      - 6379:6379
    depends_on:
      - db
    env_file:
      - .env
    privileged: true
  db:
    image: "postgres:13"
    restart: "always"
    container_name: "pg-redis-nest"
    ports:
      - 5432:5432
    env_file:
      - ".env"
    volumes:
      # keeps the Docker __dir out of the codebase
      - "../../Docker/2022/pgredisnest:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    privileged: true
volumes:
  postgres:
    name: pg-redis-nest
