version: '3.8'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    env_file:
      - .env
    privileged: true
  db:
    image: postgres:13
    container_name: postgres-prisma-migrate
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ../../Docker/2022/postgres:/var/lib/postgresql/data
    privileged: true
volumes:
  postgres:
    name: postgres-prisma-migrate
