
schema:
  - "http://localhost:3000/graphql"
  - headers:
    - authorization: "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZmUyNzFlMC1jMGM0LTQ3YWEtOGJjYi1hOTVhOTgwMjJiOTciLCJpYXQiOjE2NDQyODU1MjMsImV4cCI6MTY0NDM3MTkyM30.WRhNaPw1ztlAzddz26LYWTSbxKAHtb081EXmcBwe272XxQ23yAU_0ypzMou3K_NWPo71Ixt_5vOo0plZNSDAew"
documents:
  - "./src/graphql/**/*.graphql"
  - "!./src/graphql/graphql.schema.graphql"
  - "!./src/swr/**/*.graphql"
  - "!./src/swr/**/*.ts"
  - "./src/graphql/**.graphql"
respectGitIgnore: true
config:
  experimentalFragments: true
  reactApolloVersion: 3
  apolloReactComponentsImportFrom: "@apollo/client/react/components"
  useIndexSignature: true
  withHooks: true
  withRefetchFn: true
plugins:
  - typescript-operations
  - typescript-react-apollo
  - named-operations-object
  - typescript-apollo-client-helpers
  - fragment-matcher:
    - config:
        useExplicitTyping: true
        apolloClientVersion: 3
cacheDir: "./src/.cache"
TSConfigFile: "./tsconfig.json"


