
schema: "./schema.gql"
documents:
  - "./src/graphql/**/*.graphql"
  - "!./src/graphql/graphql.schema.graphql"
  - "!./src/swr/**/*.graphql"
  - "!./src/swr/**/*.ts"
  - "./src/graphql/graphql.ts"
respectGitIgnore: true
config:
  reactApolloVersion: 3
  apolloReactComponentsImportFrom: "@apollo/client/react/components"
  useIndexSignature: true
  withHooks: true
  withRefetchFn: true
  ContextType: "./src/apollo/resolver-context.ts#Context"
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: "./src/.cache"
TSConfigFile: "./tsconfig.json"
contextType: "./src/apollo/resolver-context.ts#Context"


