
schema:
  - "http://localhost:3000/graphql"
  - headers:
    - "authorization": "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NmE3NDY1My05MTg4LTQ2YTQtYjNiOS1lMTYwMzhjMTNjOGMiLCJpYXQiOjE2NDQ0NDEzNTYsImV4cCI6MTY0NDUyNzc1Nn0.2D7ZjaCEJNJzRh4K7dEXUkxuvh0uKJ4nZoiEdr_-INyy_Qw7kIQ_uNYriB92YxbryCfnZ788Q7TpkeDubVBsyA"
documents:
  - "./src/graphql/**/*.graphql"
  - "!./src/graphql/graphql.schema.graphql"
  - "!./src/swr/**/*.graphql"
  - "!./src/swr/**/*.ts"
  - "./src/graphql/**.graphql"
respectGitIgnore: true
config:
  experimentalFragments: true
  reactApolloVersion: 3
  apolloReactComponentsImportFrom: "@apollo/client/react/components"
  useIndexSignature: true
  withHooks: true
  withRefetchFn: true
plugins:
  - typescript-operations
  - typescript-react-apollo
  - named-operations-object
  - typescript-apollo-client-helpers
  - fragment-matcher:
    - config:
        useExplicitTyping: true
        apolloClientVersion: 3
cacheDir: "./src/.cache"
TSConfigFile: "./tsconfig.json"


